// 空港データの一覧
const airportData = [
  { name: "成田国際空港", iata: "NRT", icao: "RJAA", type: "国際線・国内線", runways: 2 },
  { name: "東京国際空港（羽田）", iata: "HND", icao: "RJTT", type: "国際線・国内線", runways: 4 },
  { name: "関西国際空港", iata: "KIX", icao: "RJBB", type: "国際線・国内線", runways: 2 },
  { name: "大阪国際空港（伊丹）", iata: "ITM", icao: "RJOO", type: "国内線専用", runways: 2 },
  { name: "新千歳空港", iata: "CTS", icao: "RJCC", type: "国際線・国内線", runways: 2 },
  { name: "福岡空港", iata: "FUK", icao: "RJFF", type: "国際線・国内線", runways: 2 },
  { name: "中部国際空港（セントレア）", iata: "NGO", icao: "RJGG", type: "国際線・国内線", runways: 1 },
  { name: "那覇空港", iata: "OKA", icao: "ROAH", type: "国際線・国内線", runways: 2 },
  { name: "仙台空港", iata: "SDJ", icao: "RJSS", type: "国際線・国内線", runways: 2 },
  { name: "茨城空港", iata: "IBR", icao: "RJAH", type: "国際線・国内線", runways: 2 },
  { name: "小松空港", iata: "KMQ", icao: "RJNK", type: "国際線・国内線", runways: 1 },
  { name: "米子鬼太郎空港", iata: "YGJ", icao: "RJOH", type: "国際線・国内線", runways: 1 },
  { name: "広島空港", iata: "HIJ", icao: "RJOA", type: "国際線・国内線", runways: 1 },
  { name: "高松空港", iata: "TAK", icao: "RJOT", type: "国際線・国内線", runways: 1 },
  { name: "松山空港", iata: "MYJ", icao: "RJOM", type: "国際線・国内線", runways: 1 },
  { name: "北九州空港", iata: "KKJ", icao: "RJFR", type: "国際線・国内線", runways: 1 },
  { name: "熊本空港", iata: "KMJ", icao: "RJFT", type: "国際線・国内線", runways: 1 },
  { name: "鹿児島空港", iata: "KOJ", icao: "RJFK", type: "国際線・国内線", runways: 1 },
  { name: "長崎空港", iata: "NGS", icao: "RJFU", type: "国際線・国内線", runways: 1 },
  { name: "旭川空港", iata: "AKJ", icao: "RJEC", type: "国際線・国内線", runways: 1 },
  { name: "函館空港", iata: "HKD", icao: "RJCH", type: "国際線・国内線", runways: 1 },
  { name: "青森空港", iata: "AOJ", icao: "RJSA", type: "国際線・国内線", runways: 1 },
  { name: "秋田空港", iata: "AXT", icao: "RJSK", type: "国内線専用", runways: 1 },
  { name: "新潟空港", iata: "KIJ", icao: "RJSN", type: "国際線・国内線", runways: 1 },
  { name: "富山空港", iata: "TOY", icao: "RJNT", type: "国際線・国内線", runways: 1 },
  { name: "静岡空港", iata: "FSZ", icao: "RJNS", type: "国際線・国内線", runways: 1 },
  { name: "岡山空港", iata: "OKJ", icao: "RJOB", type: "国際線・国内線", runways: 1 },
  { name: "山口宇部空港", iata: "UBJ", icao: "RDCU", type: "国内線専用", runways: 1 },
  { name: "徳島空港", iata: "TKS", icao: "RJOS", type: "国内線専用", runways: 1 },
  { name: "高知龍馬空港", iata: "KCZ", icao: "RJOK", type: "国内線専用", runways: 1 },
  { name: "大分空港", iata: "OIT", icao: "RJFO", type: "国際線・国内線", runways: 1 },
  { name: "宮崎ブーゲンビリア空港", iata: "KMI", icao: "RJFM", type: "国際線・国内線", runways: 1 },
  { name: "石垣空港（南ぬ島）", iata: "ISG", icao: "ROIG", type: "国際線・国内線", runways: 1 },
  { name: "宮古空港", iata: "MMY", icao: "ROMY", type: "国内線専用", runways: 1 },
  { name: "下地島空港", iata: "SHI", icao: "RORS", type: "国際線・国内線", runways: 1 },
  { name: "神戸空港", iata: "UKB", icao: "RJBE", type: "国際線・国内線", runways: 1 } // 国際チャーター・民間開放対応
];
